name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  cq:
    name: Code Quality & Test
    runs-on: ubuntu-latest

    if: |
      !contains(github.event.head_commit.message, 'docs:') &&
      !contains(github.event.head_commit.message, 'chore:') &&
      !contains(github.event.head_commit.message, '[skip ci]')

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - run: uv python install 3.11.5

      - run: uv sync --frozen

      - run: uv run ruff format --check .

      - run: uv run ruff check . --output-format=github

      - run: uv run mypy .

      - run: uv run pytest
